name: GroupJoin
main: Himbeer\GroupJoin\Main
version: 1.1.0
api: 4.0.0
author: Himbeer
website: himbeer.me
description: Get notified when a player from a specific PurePerms group joins.
softdepend:
  - PurePerms
  - GroupsAPI
  - GroupSystem