name: GroupJoin
main: Himbeer\GroupJoin\Main
version: 0.0.1
api: 3.0.0
author: Himbeer
website: himbeer.me
description: Get notified when a player from a specific PurePerms group joins.
depend:
  - PurePerms