name: GroupJoin
main: Himbeer\GroupJoin\Main
version: 2.0.0
api:
  - 4.4.0
  - 5.0.0
author: Himbeer
website: himbeer.me
description: Get notified when a player from a specific PurePerms/GroupsAPI/GroupSystem/RankSystem group joins.
softdepend:
  - PurePerms
  - GroupsAPI
  - GroupSystem
  - RankSystem